# Generated by Django 4.2.7 on 2023-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('date', models.DateField()),
                ('repeats', models.BooleanField()),
                ('start_time', models.TimeField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('posting_club', models.CharField(max_length=100)),
            ],
        ),
    ]
