# Generated by Django 4.2.7 on 2023-11-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
