# Generated by Django 4.2.7 on 2023-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeats',
            field=models.BooleanField(default=False),
        ),
    ]
