# Generated by Django 4.2.7 on 2023-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upload',
            field=models.ImageField(blank=True, default='', upload_to='static'),
        ),
    ]
