# Generated by Django 4.2.7 on 2023-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upload',
            field=models.ImageField(blank=True, default='', upload_to='events/static'),
        ),
    ]
