# Generated by Django 4.2.7 on 2023-11-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='upload',
        ),
    ]
